-- ═══════════════════════════════════════════════════════════════════════
-- COMPTES UTILISATEURS — Supabase comme source de vérité unique
-- ═══════════════════════════════════════════════════════════════════════
--
-- Modèle de sécurité
-- ------------------
-- La clé `anon` embarquée dans l'application N'EST PAS un secret : elle
-- se lit dans le binaire. Toute la sécurité repose donc sur cette RLS et
-- sur les fonctions SECURITY DEFINER ci-dessous :
--
--   * `app_users` n'est JAMAIS lisible par le rôle anon. Le hash du mot
--     de passe ne quitte donc jamais le serveur.
--   * L'app lit la liste des comptes via la vue `app_users_public`, qui
--     n'expose pas le hash.
--   * La vérification du mot de passe se fait par `bs_verify_login()` :
--     le mot de passe est comparé côté serveur avec crypt().
--   * Toute modification de compte exige les identifiants d'un compte
--     admin/super admin, vérifiés à l'intérieur de la fonction. Posséder
--     la clé anon ne suffit donc pas à créer un compte.
--
-- À exécuter dans Supabase → SQL Editor. Idempotent : rejouable.

-- pgcrypto fournit crypt() / gen_salt() / gen_random_bytes().
-- Sur Supabase, l'extension vit dans le schéma `extensions`, PAS dans
-- `public`. C'est pourquoi chaque fonction ci-dessous fige
-- `search_path = public, extensions` : sans ça, Postgres répond
-- « function crypt(text, text) does not exist ».
create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

-- Vérif : doit renvoyer une ligne (schéma le plus souvent `extensions`).
--   select extname, nspname from pg_extension e
--     join pg_namespace n on n.oid = e.extnamespace
--    where extname = 'pgcrypto';

-- ── 1. Table des comptes ───────────────────────────────────────────────
create table if not exists public.app_users (
  id            bigint generated by default as identity primary key,
  login         text        not null,
  full_name     text        not null,
  password_hash text        not null,
  role          smallint    not null default 2,  -- cf. DbUserRole côté app
  active        boolean     not null default true,
  created_at    timestamptz not null default now(),
  last_login    timestamptz,
  updated_at    timestamptz not null default now()
);

-- Login unique, insensible à la casse : « Sabrina » et « sabrina » sont
-- le même compte (convention métier de l'app).
create unique index if not exists app_users_login_lower_key
  on public.app_users (lower(login));

-- ── 2. Rate-limit des tentatives de connexion ──────────────────────────
create table if not exists public.app_login_attempts (
  login        text        not null,
  attempted_at timestamptz not null default now(),
  success      boolean     not null
);
create index if not exists app_login_attempts_login_time_idx
  on public.app_login_attempts (lower(login), attempted_at desc);

-- ── 3. RLS : personne ne lit la table directement ──────────────────────
alter table public.app_users          enable row level security;
alter table public.app_login_attempts enable row level security;
-- Aucune policy = aucun accès pour anon/authenticated. Les fonctions
-- SECURITY DEFINER ci-dessous contournent la RLS de façon contrôlée.
revoke all on public.app_users          from anon, authenticated;
revoke all on public.app_login_attempts from anon, authenticated;

-- ── 4. Vue publique : la liste des comptes, sans le hash ───────────────
create or replace view public.app_users_public as
  select id, login, full_name, role, active, created_at, last_login
  from public.app_users;

-- La vue doit s'exécuter avec les droits de son PROPRIÉTAIRE, pas de
-- l'appelant : c'est ce qui lui permet de lire app_users alors que anon
-- n'y a aucun droit. C'est déjà le comportement par défaut ; sur PG 15+
-- on le fige explicitement. L'option n'existe pas avant PG 15 — d'où le
-- bloc tolérant plutôt qu'un ALTER qui ferait tout échouer.
do $$
begin
  execute 'alter view public.app_users_public set (security_invoker = off)';
exception when others then
  raise notice 'security_invoker non supporté (PG < 15) — comportement par défaut déjà correct.';
end$$;
grant select on public.app_users_public to anon, authenticated;

-- ── 5. Helpers internes ────────────────────────────────────────────────

-- Vérifie un couple login/mot de passe et renvoie la ligne, ou null.
create or replace function public.bs_check_credentials(
  p_login text, p_password text
) returns public.app_users
language sql security definer set search_path = public, extensions as $$
  select u.* from public.app_users u
   where lower(u.login) = lower(trim(p_login))
     and u.active
     and u.password_hash = crypt(p_password, u.password_hash)
   limit 1;
$$;

-- L'acteur d'une opération d'administration doit être un compte
-- admin (role 1) ou super admin (role 0) valide. Lève une exception
-- sinon — l'app la présente telle quelle à l'utilisateur.
create or replace function public.bs_require_admin(
  p_actor_login text, p_actor_password text
) returns public.app_users
language plpgsql security definer set search_path = public, extensions as $$
declare actor public.app_users;
begin
  actor := public.bs_check_credentials(p_actor_login, p_actor_password);
  if actor.id is null then
    raise exception 'IDENTIFIANTS_ADMIN_INVALIDES';
  end if;
  if actor.role not in (0, 1) then
    raise exception 'DROITS_INSUFFISANTS';
  end if;
  return actor;
end;
$$;

-- ── 6. Connexion ───────────────────────────────────────────────────────
--
-- Renvoie le compte (sans le hash) ou une erreur métier lisible.
-- Rate-limit : 5 échecs sur 5 minutes pour un même login → refus.
create or replace function public.bs_verify_login(
  p_login text, p_password text
) returns json
language plpgsql security definer set search_path = public, extensions as $$
declare
  u       public.app_users;
  fails   int;
  exists_ boolean;
begin
  select count(*) into fails
    from public.app_login_attempts
   where lower(login) = lower(trim(p_login))
     and not success
     and attempted_at > now() - interval '5 minutes';

  if fails >= 5 then
    return json_build_object('status', 'locked_out', 'retry_after_seconds', 300);
  end if;

  u := public.bs_check_credentials(p_login, p_password);

  if u.id is null then
    insert into public.app_login_attempts (login, success)
      values (trim(p_login), false);
    select exists(
      select 1 from public.app_users
       where lower(login) = lower(trim(p_login))
    ) into exists_;
    if not exists_ then
      return json_build_object('status', 'unknown_user');
    end if;
    -- Compte existant mais désactivé → message distinct.
    if exists(select 1 from public.app_users
               where lower(login) = lower(trim(p_login)) and not active) then
      return json_build_object('status', 'inactive');
    end if;
    return json_build_object('status', 'bad_password');
  end if;

  insert into public.app_login_attempts (login, success) values (u.login, true);
  update public.app_users set last_login = now() where id = u.id;

  return json_build_object(
    'status', 'ok',
    'user', json_build_object(
      'id', u.id, 'login', u.login, 'full_name', u.full_name,
      'role', u.role, 'active', u.active,
      'created_at', u.created_at, 'last_login', now()
    )
  );
end;
$$;

-- ── 7. Administration des comptes ──────────────────────────────────────
-- Chaque fonction exige les identifiants d'un admin : la clé anon seule
-- ne permet AUCUNE écriture.

create or replace function public.bs_create_account(
  p_actor_login text, p_actor_password text,
  p_login text, p_full_name text, p_password text, p_role smallint
) returns json
language plpgsql security definer set search_path = public, extensions as $$
declare actor public.app_users; new_id bigint;
begin
  actor := public.bs_require_admin(p_actor_login, p_actor_password);
  -- Seul un super admin (0) crée un admin (1) ou un autre super admin.
  if p_role in (0, 1) and actor.role <> 0 then
    raise exception 'DROITS_INSUFFISANTS';
  end if;
  if length(trim(p_login)) < 2 then
    raise exception 'LOGIN_TROP_COURT';
  end if;
  if length(p_password) < 4 then
    raise exception 'MOT_DE_PASSE_TROP_COURT';
  end if;
  if exists (select 1 from public.app_users
              where lower(login) = lower(trim(p_login))) then
    raise exception 'LOGIN_DEJA_PRIS';
  end if;

  insert into public.app_users (login, full_name, password_hash, role)
  values (trim(p_login), trim(p_full_name),
          crypt(p_password, gen_salt('bf', 12)), p_role)
  returning id into new_id;

  return json_build_object('status', 'ok', 'id', new_id);
end;
$$;

create or replace function public.bs_set_password(
  p_actor_login text, p_actor_password text,
  p_login text, p_new_password text
) returns json
language plpgsql security definer set search_path = public, extensions as $$
declare actor public.app_users; target public.app_users;
begin
  select * into target from public.app_users
   where lower(login) = lower(trim(p_login));
  if target.id is null then raise exception 'COMPTE_INTROUVABLE'; end if;

  -- Changer SON PROPRE mot de passe ne demande aucun privilège : il
  -- suffit de prouver qu'on connaît l'actuel. Changer celui d'un autre
  -- exige d'être admin.
  actor := public.bs_check_credentials(p_actor_login, p_actor_password);
  if actor.id is null then
    raise exception 'IDENTIFIANTS_ADMIN_INVALIDES';
  end if;
  if actor.id <> target.id then
    if actor.role not in (0, 1) then
      raise exception 'DROITS_INSUFFISANTS';
    end if;
    -- Seul un super admin touche au mot de passe d'un admin.
    if target.role in (0, 1) and actor.role <> 0 then
      raise exception 'DROITS_INSUFFISANTS';
    end if;
  end if;

  if length(p_new_password) < 4 then
    raise exception 'MOT_DE_PASSE_TROP_COURT';
  end if;

  update public.app_users
     set password_hash = crypt(p_new_password, gen_salt('bf', 12)),
         updated_at    = now()
   where id = target.id;
  -- Un changement de mot de passe purge le compteur d'échecs.
  delete from public.app_login_attempts where lower(login) = lower(target.login);
  return json_build_object('status', 'ok');
end;
$$;

create or replace function public.bs_set_active(
  p_actor_login text, p_actor_password text,
  p_login text, p_active boolean
) returns json
language plpgsql security definer set search_path = public, extensions as $$
declare actor public.app_users; target public.app_users;
begin
  actor := public.bs_require_admin(p_actor_login, p_actor_password);
  select * into target from public.app_users
   where lower(login) = lower(trim(p_login));
  if target.id is null then raise exception 'COMPTE_INTROUVABLE'; end if;
  if target.id = actor.id then raise exception 'AUTO_DESACTIVATION'; end if;
  if target.role in (0, 1) and actor.role <> 0 then
    raise exception 'DROITS_INSUFFISANTS';
  end if;

  update public.app_users set active = p_active, updated_at = now()
   where id = target.id;
  return json_build_object('status', 'ok');
end;
$$;

create or replace function public.bs_rename_account(
  p_actor_login text, p_actor_password text,
  p_login text, p_full_name text
) returns json
language plpgsql security definer set search_path = public, extensions as $$
declare actor public.app_users;
begin
  actor := public.bs_require_admin(p_actor_login, p_actor_password);
  if not exists (select 1 from public.app_users
                  where lower(login) = lower(trim(p_login))) then
    raise exception 'COMPTE_INTROUVABLE';
  end if;
  update public.app_users
     set full_name = trim(p_full_name), updated_at = now()
   where lower(login) = lower(trim(p_login));
  return json_build_object('status', 'ok');
end;
$$;

create or replace function public.bs_delete_account(
  p_actor_login text, p_actor_password text, p_login text
) returns json
language plpgsql security definer set search_path = public, extensions as $$
declare actor public.app_users; target public.app_users;
begin
  actor := public.bs_require_admin(p_actor_login, p_actor_password);
  select * into target from public.app_users
   where lower(login) = lower(trim(p_login));
  if target.id is null then raise exception 'COMPTE_INTROUVABLE'; end if;
  if target.id = actor.id then raise exception 'AUTO_SUPPRESSION'; end if;
  -- Un super admin ne se supprime que par un autre super admin, et
  -- jamais le dernier : on ne se verrouille pas dehors.
  if target.role = 0 then
    if actor.role <> 0 then raise exception 'DROITS_INSUFFISANTS'; end if;
    if (select count(*) from public.app_users
         where role = 0 and active) <= 1 then
      raise exception 'DERNIER_SUPER_ADMIN';
    end if;
  end if;

  delete from public.app_users where id = target.id;
  return json_build_object('status', 'ok');
end;
$$;

-- ── 8. Droits d'exécution ──────────────────────────────────────────────
--
-- ⚠️ POINT CRITIQUE : PostgreSQL accorde EXECUTE à PUBLIC sur toute
-- nouvelle fonction. Un `revoke ... from anon, authenticated` NE SUFFIT
-- PAS — le droit PUBLIC reste, et la clé anon (extractible du binaire)
-- peut alors appeler les helpers internes, dont celui qui renvoie le
-- hash du mot de passe. Il faut retirer PUBLIC d'abord, puis accorder
-- explicitement ce qui doit l'être.

-- 8.a Tout fermer, PUBLIC compris.
revoke execute on function public.bs_check_credentials(text, text) from public, anon, authenticated;
revoke execute on function public.bs_require_admin(text, text)     from public, anon, authenticated;
revoke execute on function public.bs_verify_login(text, text)      from public, anon, authenticated;
revoke execute on function public.bs_create_account(text, text, text, text, text, smallint) from public, anon, authenticated;
revoke execute on function public.bs_set_password(text, text, text, text)   from public, anon, authenticated;
revoke execute on function public.bs_set_active(text, text, text, boolean)  from public, anon, authenticated;
revoke execute on function public.bs_rename_account(text, text, text, text) from public, anon, authenticated;
revoke execute on function public.bs_delete_account(text, text, text)       from public, anon, authenticated;

-- 8.b Les futures fonctions de ce schéma ne seront pas exposées non plus.
alter default privileges in schema public revoke execute on functions from public;

grant execute on function public.bs_verify_login(text, text)      to anon, authenticated;
grant execute on function public.bs_create_account(text, text, text, text, text, smallint) to anon, authenticated;
grant execute on function public.bs_set_password(text, text, text, text)   to anon, authenticated;
grant execute on function public.bs_set_active(text, text, text, boolean)  to anon, authenticated;
grant execute on function public.bs_rename_account(text, text, text, text) to anon, authenticated;
grant execute on function public.bs_delete_account(text, text, text)       to anon, authenticated;
-- Les helpers restent internes : ils ne sont JAMAIS regrantés. Seules
-- les fonctions ci-dessus, qui contrôlent elles-mêmes l'autorisation,
-- sont exposées à la clé anon.
--
-- Vérification (doit renvoyer 0 ligne) :
--   select p.proname
--   from   pg_proc p join pg_namespace n on n.oid = p.pronamespace
--   where  n.nspname = 'public' and p.proname in
--            ('bs_check_credentials','bs_require_admin','bs_new_import_token')
--     and  has_function_privilege('anon', p.oid, 'EXECUTE');

-- ── 9. Amorçage : un premier super admin ───────────────────────────────
-- REMPLACE le mot de passe ci-dessous, puis exécute UNE FOIS. Sans ce
-- compte, aucune administration n'est possible depuis l'app.
insert into public.app_users (login, full_name, password_hash, role)
select 'pamela', 'Pamela — Super Admin',
       crypt('CHANGE-MOI-AVANT-EXECUTION', gen_salt('bf', 12)), 0
where not exists (select 1 from public.app_users where role = 0);

-- ── 10. Purge des anciennes tentatives (à planifier si pg_cron dispo) ──
delete from public.app_login_attempts
 where attempted_at < now() - interval '7 days';

-- ── 11. Nettoyage : l'ancien miroir de comptes n'a plus de raison d'être
--    Les comptes ne transitent plus par `mirror_users`. On la garde le
--    temps de la bascule ; décommente pour la supprimer définitivement.
-- drop table if exists public.mirror_users;

notify pgrst, 'reload schema';
